name: danbishop-snapclient
version: "0.26"
summary: Snapcast
description: |
  Snapcast is a multiroom client-server
  audio player, where all clients are
  time synchronized with the server to
  play perfectly synced audio.

confinement: strict
base: core20
grade: stable

parts:

  boost:
    plugin: dump
    source: https://sourceforge.net/projects/boost/files/boost/1.79.0/boost_1_79_0.tar.bz2
    source-checksum: sha1/31209dcff292bd6a64e5e08ceb3ce44a33615dc0
    stage:
      - boost/
    # prime:
    #   - -*

  snapclient:
    plugin: cmake
    after: [boost]
    source: https://github.com/badaix/snapcast.git
    #source-subdir: client
    build-packages:
      - g++
      - make
      - build-essential
      - pkg-config
      - libasound2-dev
      - libpulse-dev
      - libvorbis-dev
      - libflac-dev
      - libopus-dev
      - libavahi-client-dev
      - libasio-dev
      - libsoxr-dev
      # - alsa-utils
      # - avahi-daemon
      - libexpat1-dev
      # - libboost-system-dev
      # - libboost-thread-dev
      # - libboost-program-options-dev
      # - libboost-test-dev
    stage-packages:
      - libasound2
      - libavahi-client3 
      - libavahi-common3
      - libflac8 
      - libgcc1 
      - libogg0 
      - libopus0 
      - libpulse0
      - libsoxr0 
      - libstdc++6
      - libvorbisidec1 
      
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

apps:
  snapclient:
    command: usr/local/bin/snapclient
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - audio-playback
      - alsa
      - avahi-control
      - network
